//! Untrusted inbound observations and the narrow human-reply/mention filter.

use std::{collections::BTreeSet, error::Error, fmt};

use repo_com_delivery::{DeliveryAttempt, DeliveryState};
use serde::{Deserialize, Serialize};

/// One attachment indicator. No URL, content, or attachment bytes are
/// represented by this type.
#[derive(Clone, Deserialize, Eq, PartialEq, Serialize)]
pub struct AttachmentIndicator {
    /// Discord attachment ID.
    pub id: String,
    /// Filename as reported by Discord.
    pub filename: String,
    /// Optional MIME type.
    pub content_type: Option<String>,
    /// Size in bytes, when Discord reports it.
    pub size: Option<u64>,
}

impl fmt::Debug for AttachmentIndicator {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AttachmentIndicator")
            .field("id", &self.id)
            .field("filename", &"[REDACTED]")
            .field("content_type", &self.content_type)
            .field("size", &self.size)
            .finish()
    }
}

/// Author facts copied from Discord without treating them as authority.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct AuthorEvidence {
    /// Discord author/user ID.
    pub user_id: String,
    /// Whether Discord marked the author as a bot.
    pub is_bot: bool,
    /// Whether the message was generated by a webhook.
    pub is_webhook: bool,
}

/// Reply/reference evidence copied from Discord.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ReplyEvidence {
    /// Whether the message contained a message reference object.
    pub reference_present: bool,
    /// Referenced message ID, when supplied by Discord.
    pub referenced_message_id: Option<String>,
    /// Referenced channel ID, when supplied by Discord.
    pub referenced_channel_id: Option<String>,
    /// Referenced guild ID, when supplied by Discord.
    pub referenced_guild_id: Option<String>,
    /// Discord reported a reply whose referenced message was deleted/missing.
    pub referenced_message_deleted: bool,
}

impl ReplyEvidence {
    /// Creates empty reply evidence.
    #[must_use]
    pub fn none() -> Self {
        Self {
            reference_present: false,
            referenced_message_id: None,
            referenced_channel_id: None,
            referenced_guild_id: None,
            referenced_message_deleted: false,
        }
    }
}

/// Mention facts copied from Discord. The adapter records evidence only; it
/// never interprets the surrounding message as an instruction.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct MentionEvidence {
    /// IDs explicitly present in Discord's structured `mentions` field.
    pub mentioned_user_ids: Vec<String>,
    /// Whether the configured bot ID was present in that field.
    pub structured_bot_mention: bool,
    /// Whether the exact Discord user-mention token appeared in raw text.
    pub textual_bot_mention: bool,
}

impl MentionEvidence {
    /// Returns whether either structured or textual evidence names the bot.
    #[must_use]
    pub fn direct_bot_mention(&self) -> bool {
        self.structured_bot_mention || self.textual_bot_mention
    }
}

/// Remote provenance for one observation.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FetchProvenance {
    /// Provider name; v1 is Discord only.
    pub provider: String,
    /// Pinned REST API version.
    pub api_version: String,
    /// Repository-local configuration identity.
    pub repository_id: String,
    /// Configured workspace identity.
    pub workspace_id: String,
    /// Configured inbound alias.
    pub alias: String,
    /// Configured channel identity.
    pub channel_id: String,
    /// Local observation time supplied by the caller or fetch clock.
    pub retrieved_at: String,
}

impl FetchProvenance {
    /// Creates Discord v10 provenance.
    #[must_use]
    pub fn discord(
        repository_id: impl Into<String>,
        workspace_id: impl Into<String>,
        alias: impl Into<String>,
        channel_id: impl Into<String>,
        retrieved_at: impl Into<String>,
    ) -> Self {
        Self {
            provider: "discord".to_owned(),
            api_version: "v10".to_owned(),
            repository_id: repository_id.into(),
            workspace_id: workspace_id.into(),
            alias: alias.into(),
            channel_id: channel_id.into(),
            retrieved_at: retrieved_at.into(),
        }
    }
}

/// Explicit trust marker carried by every inbound envelope.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum InboundTrust {
    /// The value is remote, untrusted data and has no authority.
    Untrusted,
}

/// One accepted inbound message, always explicitly marked untrusted.
#[derive(Clone, Deserialize, Eq, PartialEq, Serialize)]
pub struct UntrustedInboundEnvelope {
    /// Repository scope used for local correlation.
    pub repository_id: String,
    /// Discord message ID.
    pub remote_message_id: String,
    /// Configured channel ID.
    pub channel_id: String,
    /// Remote author evidence.
    pub author: AuthorEvidence,
    /// Remote message timestamp, retained as untrusted text.
    pub timestamp: String,
    /// Exact remote message text; it is never parsed as an instruction.
    pub text: String,
    /// Reply/reference evidence.
    #[serde(rename = "reply_context")]
    pub reply: ReplyEvidence,
    /// Direct mention evidence.
    #[serde(rename = "mention_evidence")]
    pub mentions: MentionEvidence,
    /// Attachment indicators only; attachment bytes are never fetched.
    pub attachment_indicators: Vec<AttachmentIndicator>,
    /// Remote provenance.
    pub provenance: FetchProvenance,
    /// Always `untrusted`.
    pub trust: InboundTrust,
}

impl fmt::Debug for UntrustedInboundEnvelope {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("UntrustedInboundEnvelope")
            .field("repository_id", &self.repository_id)
            .field("remote_message_id", &self.remote_message_id)
            .field("channel_id", &self.channel_id)
            .field("author", &self.author)
            .field("timestamp", &self.timestamp)
            .field("text", &"[REDACTED]")
            .field("reply", &self.reply)
            .field("mentions", &self.mentions)
            .field("attachment_indicators", &self.attachment_indicators)
            .field("provenance", &self.provenance)
            .field("trust", &self.trust)
            .finish()
    }
}

impl UntrustedInboundEnvelope {
    /// Returns whether this envelope is explicitly untrusted.
    #[must_use]
    pub const fn is_untrusted(&self) -> bool {
        matches!(self.trust, InboundTrust::Untrusted)
    }

    /// Explicit alias for [`Self::is_untrusted`].
    #[must_use]
    pub const fn untrusted(&self) -> bool {
        self.is_untrusted()
    }

    /// Returns the remote message ID.
    #[must_use]
    pub fn message_id(&self) -> &str {
        &self.remote_message_id
    }

    /// Returns the remote author ID.
    #[must_use]
    pub fn author_id(&self) -> &str {
        &self.author.user_id
    }

    /// Returns reply/reference evidence.
    #[must_use]
    pub fn reply_context(&self) -> &ReplyEvidence {
        &self.reply
    }

    /// Returns direct mention evidence.
    #[must_use]
    pub fn mention_evidence(&self) -> &MentionEvidence {
        &self.mentions
    }

    /// Returns the exact remote text without interpreting it.
    #[must_use]
    pub fn text(&self) -> &str {
        &self.text
    }

    /// Returns the attachment indicators without exposing bytes.
    #[must_use]
    pub fn attachments(&self) -> &[AttachmentIndicator] {
        &self.attachment_indicators
    }
}

/// Compatibility names used by the feature contract.
pub type InboundEnvelope = UntrustedInboundEnvelope;
/// Compatibility name emphasizing the trust boundary.
pub type UntrustedEnvelope = UntrustedInboundEnvelope;

/// A raw, validated Discord message projection used by the filter and tests.
#[derive(Clone, Eq, PartialEq)]
pub struct RemoteMessage {
    /// Discord message ID.
    pub id: String,
    /// Channel containing the message.
    pub channel_id: String,
    /// Author ID.
    pub author_id: String,
    /// Whether Discord marked the author as a bot.
    pub author_is_bot: bool,
    /// Whether Discord identified a webhook author.
    pub webhook_id: Option<String>,
    /// Exact message text.
    pub content: String,
    /// Message timestamp.
    pub timestamp: String,
    /// Edit timestamp, when present.
    pub edited_timestamp: Option<String>,
    /// Structured user mentions.
    pub mentioned_user_ids: Vec<String>,
    /// Reply/reference facts.
    pub reply: ReplyEvidence,
    /// Attachment indicators.
    pub attachments: Vec<AttachmentIndicator>,
    /// Discord message type.
    pub message_type: u64,
}

impl fmt::Debug for RemoteMessage {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RemoteMessage")
            .field("id", &self.id)
            .field("channel_id", &self.channel_id)
            .field("author_id", &self.author_id)
            .field("author_is_bot", &self.author_is_bot)
            .field("webhook_id", &self.webhook_id)
            .field("content", &"[REDACTED]")
            .field("timestamp", &self.timestamp)
            .field("edited_timestamp", &self.edited_timestamp)
            .field("mentioned_user_ids", &self.mentioned_user_ids)
            .field("reply", &self.reply)
            .field("attachments", &self.attachments)
            .field("message_type", &self.message_type)
            .finish()
    }
}

impl RemoteMessage {
    /// Creates a simple remote message for focused filtering tests.
    #[must_use]
    pub fn new(
        id: impl Into<String>,
        channel_id: impl Into<String>,
        author_id: impl Into<String>,
        content: impl Into<String>,
        timestamp: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            channel_id: channel_id.into(),
            author_id: author_id.into(),
            author_is_bot: false,
            webhook_id: None,
            content: content.into(),
            timestamp: timestamp.into(),
            edited_timestamp: None,
            mentioned_user_ids: Vec::new(),
            reply: ReplyEvidence::none(),
            attachments: Vec::new(),
            message_type: 0,
        }
    }

    /// Adds structured mention IDs.
    #[must_use]
    pub fn with_mentions(mut self, values: impl IntoIterator<Item = String>) -> Self {
        self.mentioned_user_ids = values.into_iter().collect();
        self
    }

    /// Adds reply evidence.
    #[must_use]
    pub fn with_reply(mut self, reply: ReplyEvidence) -> Self {
        self.reply = reply;
        self
    }

    /// Marks the author as a bot.
    #[must_use]
    pub fn bot(mut self) -> Self {
        self.author_is_bot = true;
        self
    }

    /// Marks the message as webhook-authored.
    #[must_use]
    pub fn webhook(mut self) -> Self {
        self.webhook_id = Some("webhook".to_owned());
        self
    }

    /// Adds attachment indicators.
    #[must_use]
    pub fn with_attachments(
        mut self,
        values: impl IntoIterator<Item = AttachmentIndicator>,
    ) -> Self {
        self.attachments = values.into_iter().collect();
        self
    }
}

/// One locally accepted delivery message that may be replied to.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct AcceptedDelivery {
    /// Repository that owns the delivery.
    pub repository_id: String,
    /// Destination channel containing the delivered message.
    pub channel_id: String,
    /// Remote Discord message ID returned by accepted delivery.
    pub remote_message_id: String,
}

impl AcceptedDelivery {
    /// Creates an accepted-delivery correlation fact.
    pub fn new(
        repository_id: impl Into<String>,
        channel_id: impl Into<String>,
        remote_message_id: impl Into<String>,
    ) -> Result<Self, AcceptedDeliveryError> {
        let value = Self {
            repository_id: repository_id.into(),
            channel_id: channel_id.into(),
            remote_message_id: remote_message_id.into(),
        };
        value.validate()?;
        Ok(value)
    }

    /// Builds a correlation fact from an accepted delivery attempt.
    pub fn from_attempt(attempt: &DeliveryAttempt) -> Result<Self, AcceptedDeliveryError> {
        if !matches!(
            attempt.state,
            DeliveryState::Accepted | DeliveryState::ReconciledAccepted
        ) {
            return Err(AcceptedDeliveryError::NotAccepted);
        }
        let remote_message_id = attempt
            .remote_message_id
            .as_deref()
            .ok_or(AcceptedDeliveryError::MissingRemoteMessageId)?;
        Self::new(
            attempt.repository_id.clone(),
            attempt.resolved_destination.channel_id.clone(),
            remote_message_id,
        )
    }

    /// Returns whether this fact matches the exact local delivery scope.
    #[must_use]
    pub fn matches(&self, repository_id: &str, channel_id: &str, message_id: &str) -> bool {
        self.repository_id == repository_id
            && self.channel_id == channel_id
            && self.remote_message_id == message_id
    }

    fn validate(&self) -> Result<(), AcceptedDeliveryError> {
        for value in [
            &self.repository_id,
            &self.channel_id,
            &self.remote_message_id,
        ] {
            if value.is_empty() || value.len() > 512 || value.chars().any(char::is_control) {
                return Err(AcceptedDeliveryError::InvalidField);
            }
        }
        Ok(())
    }
}

/// Compatibility name for the local accepted-delivery fact.
pub type AcceptedLocalDelivery = AcceptedDelivery;

/// A safe accepted-delivery validation error.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AcceptedDeliveryError {
    /// One correlation field was empty, unsafe, or too long.
    InvalidField,
    /// The delivery attempt was not accepted or reconciled accepted.
    NotAccepted,
    /// The accepted attempt did not contain a remote message ID.
    MissingRemoteMessageId,
}

impl fmt::Display for AcceptedDeliveryError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::InvalidField => "accepted delivery correlation field is invalid",
            Self::NotAccepted => "delivery attempt is not accepted",
            Self::MissingRemoteMessageId => "accepted delivery has no remote message ID",
        })
    }
}

impl Error for AcceptedDeliveryError {}

/// The exact local context used to decide whether a raw message is retained.
#[derive(Clone, Copy)]
pub struct FilterContext<'a> {
    /// Repository identity from the current configuration.
    pub repository_id: &'a str,
    /// Configured inbound channel.
    pub channel_id: &'a str,
    /// Configured bot user ID.
    pub bot_user_id: &'a str,
    /// Locally accepted deliveries.
    pub accepted_deliveries: &'a [AcceptedDelivery],
}

impl<'a> FilterContext<'a> {
    /// Creates a validated filter context.
    pub fn new(
        repository_id: &'a str,
        channel_id: &'a str,
        bot_user_id: &'a str,
        accepted_deliveries: &'a [AcceptedDelivery],
    ) -> Result<Self, FilterError> {
        if !safe_component(repository_id)
            || !safe_component(channel_id)
            || !safe_component(bot_user_id)
        {
            return Err(FilterError::InvalidContext);
        }
        Ok(Self {
            repository_id,
            channel_id,
            bot_user_id,
            accepted_deliveries,
        })
    }
}

/// A safe filtering/configuration error.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FilterError {
    /// A repository, channel, or bot identity was unsafe.
    InvalidContext,
}

impl fmt::Display for FilterError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("inbound filter context is invalid")
    }
}

impl Error for FilterError {}

/// Returns whether a raw message is a human reply to an accepted local
/// delivery or a direct mention of the configured bot.
#[must_use]
pub fn should_retain(message: &RemoteMessage, context: &FilterContext<'_>) -> bool {
    if !safe_component(&message.id)
        || !safe_component(&message.channel_id)
        || !safe_component(&message.author_id)
        || message.channel_id != context.channel_id
        || message.author_id == context.bot_user_id
        || message.author_is_bot
        || message.webhook_id.is_some()
        || !matches!(message.message_type, 0 | 19)
    {
        return false;
    }

    let structured_mention = message
        .mentioned_user_ids
        .iter()
        .any(|value| value == context.bot_user_id);
    let textual_mention = contains_user_mention(&message.content, context.bot_user_id);
    if structured_mention || textual_mention {
        return true;
    }

    if !message.reply.reference_present {
        return false;
    }
    let Some(referenced_id) = message.reply.referenced_message_id.as_deref() else {
        return false;
    };
    let same_channel = message
        .reply
        .referenced_channel_id
        .as_deref()
        .is_none_or(|value| value == context.channel_id);
    same_channel
        && context.accepted_deliveries.iter().any(|delivery| {
            delivery.matches(context.repository_id, context.channel_id, referenced_id)
        })
}

/// Converts a retained message into an explicit untrusted envelope.
#[must_use]
pub fn to_untrusted_envelope(
    message: &RemoteMessage,
    context: &FilterContext<'_>,
    provenance: FetchProvenance,
) -> UntrustedInboundEnvelope {
    let structured_bot_mention = message
        .mentioned_user_ids
        .iter()
        .any(|value| value == context.bot_user_id);
    let textual_bot_mention = contains_user_mention(&message.content, context.bot_user_id);
    let mentioned_user_ids = message
        .mentioned_user_ids
        .iter()
        .filter(|value| safe_component(value))
        .cloned()
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>();

    UntrustedInboundEnvelope {
        repository_id: context.repository_id.to_owned(),
        remote_message_id: message.id.clone(),
        channel_id: message.channel_id.clone(),
        author: AuthorEvidence {
            user_id: message.author_id.clone(),
            is_bot: message.author_is_bot,
            is_webhook: message.webhook_id.is_some(),
        },
        timestamp: message.timestamp.clone(),
        text: message.content.clone(),
        reply: message.reply.clone(),
        mentions: MentionEvidence {
            mentioned_user_ids,
            structured_bot_mention,
            textual_bot_mention,
        },
        attachment_indicators: message.attachments.clone(),
        provenance,
        trust: InboundTrust::Untrusted,
    }
}

/// Filters a sequence in deterministic remote-ID order.
#[must_use]
pub fn filter_messages(
    messages: &[RemoteMessage],
    context: &FilterContext<'_>,
    provenance: impl Fn(&RemoteMessage) -> FetchProvenance,
) -> Vec<UntrustedInboundEnvelope> {
    let mut ordered = messages.to_vec();
    ordered.sort_by(|left, right| compare_message_ids(&left.id, &right.id));
    ordered
        .iter()
        .filter(|message| should_retain(message, context))
        .map(|message| to_untrusted_envelope(message, context, provenance(message)))
        .collect()
}

fn compare_message_ids(left: &str, right: &str) -> std::cmp::Ordering {
    match (left.parse::<u128>(), right.parse::<u128>()) {
        (Ok(left), Ok(right)) => left.cmp(&right),
        _ => left.cmp(right),
    }
}

fn contains_user_mention(content: &str, bot_user_id: &str) -> bool {
    content.contains(&format!("<@{bot_user_id}>"))
        || content.contains(&format!("<@!{bot_user_id}>"))
}

fn safe_component(value: &str) -> bool {
    !value.is_empty() && value.len() <= 512 && !value.chars().any(char::is_control)
}

#[cfg(test)]
mod tests {
    use super::{
        AcceptedDelivery, AttachmentIndicator, FilterContext, RemoteMessage, ReplyEvidence,
        should_retain,
    };

    const REPO: &str = "repo-a";
    const CHANNEL: &str = "channel-1";
    const BOT: &str = "bot-1";

    fn context<'a>(accepted: &'a [AcceptedDelivery]) -> FilterContext<'a> {
        FilterContext::new(REPO, CHANNEL, BOT, accepted).expect("context")
    }

    #[test]
    fn only_human_replies_or_direct_bot_mentions_are_retained() {
        let accepted = vec![AcceptedDelivery::new(REPO, CHANNEL, "sent-1").expect("accepted")];
        let reply = RemoteMessage::new("reply-1", CHANNEL, "human-1", "body", "t").with_reply(
            ReplyEvidence {
                reference_present: true,
                referenced_message_id: Some("sent-1".to_owned()),
                referenced_channel_id: Some(CHANNEL.to_owned()),
                referenced_guild_id: None,
                referenced_message_deleted: false,
            },
        );
        assert!(should_retain(&reply, &context(&accepted)));

        let mention = RemoteMessage::new("mention-1", CHANNEL, "human-2", "hello", "t")
            .with_mentions([BOT.to_owned()]);
        assert!(should_retain(&mention, &context(&accepted)));

        let unrelated = RemoteMessage::new("other-1", CHANNEL, "human-3", "hello", "t");
        assert!(!should_retain(&unrelated, &context(&accepted)));
        assert!(!should_retain(&reply.clone().bot(), &context(&accepted)));
        assert!(!should_retain(
            &reply.clone().webhook(),
            &context(&accepted)
        ));
        let cross_repo = AcceptedDelivery::new("repo-b", CHANNEL, "sent-1").expect("cross repo");
        assert!(!should_retain(&reply, &context(&[cross_repo])));
    }

    #[test]
    fn attachment_projection_has_indicators_only() {
        let message = RemoteMessage::new("m", CHANNEL, "h", "x", "t").with_attachments([
            AttachmentIndicator {
                id: "a".to_owned(),
                filename: "private.txt".to_owned(),
                content_type: Some("text/plain".to_owned()),
                size: Some(4),
            },
        ]);
        let serialized = serde_json::to_string(&message.attachments).expect("attachments JSON");
        assert!(serialized.contains("private.txt"));
        assert!(!serialized.contains("url"));
        assert!(!serialized.contains("bytes"));
    }
}
